/* =========================================================
   0. 기존 테이블 초기화
   개발 초기에만 사용
   ========================================================= */

DROP TABLE IF EXISTS paper_code_mappings CASCADE;
DROP TABLE IF EXISTS code_blocks CASCADE;
DROP TABLE IF EXISTS paper_repositories CASCADE;
DROP TABLE IF EXISTS paper_chunks CASCADE;
DROP TABLE IF EXISTS repositories CASCADE;
DROP TABLE IF EXISTS papers CASCADE;


/* =========================================================
   1. 논문
   ========================================================= */

CREATE TABLE papers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title TEXT NOT NULL,
    abstract TEXT,

    arxiv_id VARCHAR(50),
    doi VARCHAR(255),

    pdf_url TEXT,
    source_url TEXT,

    published_date DATE,

    authors JSONB NOT NULL DEFAULT '[]'::jsonb,

    processing_status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (
            processing_status IN (
                'PENDING',
                'PROCESSING',
                'COMPLETED',
                'FAILED'
            )
        ),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_papers_arxiv_id UNIQUE (arxiv_id),
    CONSTRAINT uq_papers_doi UNIQUE (doi)
);


/* =========================================================
   2. 논문 청크
   ========================================================= */

CREATE TABLE paper_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    paper_id BIGINT NOT NULL,

    section_title VARCHAR(255),
    subsection_title VARCHAR(255),

    chunk_index INTEGER NOT NULL,
    content TEXT NOT NULL,

    page_start INTEGER,
    page_end INTEGER,

    token_count INTEGER,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_paper_chunks_paper
        FOREIGN KEY (paper_id)
        REFERENCES papers(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_paper_chunks_order
        UNIQUE (paper_id, chunk_index),

    CONSTRAINT ck_paper_chunks_page
        CHECK (
            page_start IS NULL
            OR page_end IS NULL
            OR page_end >= page_start
        )
);


/* =========================================================
   3. GitHub 저장소
   ========================================================= */

CREATE TABLE repositories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    github_url TEXT NOT NULL,
    owner_name VARCHAR(255),
    repository_name VARCHAR(255) NOT NULL,

    default_branch VARCHAR(100),
    commit_hash VARCHAR(100),

    license_name VARCHAR(100),
    primary_language VARCHAR(100),

    star_count INTEGER NOT NULL DEFAULT 0,

    processing_status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (
            processing_status IN (
                'PENDING',
                'CLONING',
                'PARSING',
                'COMPLETED',
                'FAILED'
            )
        ),

    last_synced_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_repositories_github_url
        UNIQUE (github_url),

    CONSTRAINT ck_repositories_star_count
        CHECK (star_count >= 0)
);


/* =========================================================
   4. 논문과 저장소 관계
   ========================================================= */

CREATE TABLE paper_repositories (
    paper_id BIGINT NOT NULL,
    repository_id BIGINT NOT NULL,

    relation_type VARCHAR(20) NOT NULL DEFAULT 'COMMUNITY'
        CHECK (
            relation_type IN (
                'OFFICIAL',
                'AUTHOR',
                'COMMUNITY',
                'REFERENCE'
            )
        ),

    is_primary BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (paper_id, repository_id),

    CONSTRAINT fk_paper_repositories_paper
        FOREIGN KEY (paper_id)
        REFERENCES papers(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_paper_repositories_repository
        FOREIGN KEY (repository_id)
        REFERENCES repositories(id)
        ON DELETE CASCADE
);


/* =========================================================
   5. 코드 블록
   ========================================================= */

CREATE TABLE code_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    repository_id BIGINT NOT NULL,

    file_path TEXT NOT NULL,

    symbol_name VARCHAR(500),

    symbol_type VARCHAR(30) NOT NULL
        CHECK (
            symbol_type IN (
                'FILE',
                'CLASS',
                'FUNCTION',
                'METHOD',
                'MODULE'
            )
        ),

    programming_language VARCHAR(50),

    start_line INTEGER,
    end_line INTEGER,

    code_content TEXT NOT NULL,

    parent_symbol_name VARCHAR(500),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_code_blocks_repository
        FOREIGN KEY (repository_id)
        REFERENCES repositories(id)
        ON DELETE CASCADE,

    CONSTRAINT ck_code_blocks_lines
        CHECK (
            start_line IS NULL
            OR end_line IS NULL
            OR end_line >= start_line
        ),

    CONSTRAINT uq_code_blocks_location
        UNIQUE (
            repository_id,
            file_path,
            symbol_name,
            start_line
        )
);


/* =========================================================
   6. 논문 청크와 코드 블록 매핑
   ========================================================= */

CREATE TABLE paper_code_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    paper_chunk_id BIGINT NOT NULL,
    code_block_id BIGINT NOT NULL,

    similarity_score NUMERIC(6, 5),

    mapping_method VARCHAR(20) NOT NULL DEFAULT 'AI'
        CHECK (
            mapping_method IN (
                'AI',
                'MANUAL',
                'HYBRID'
            )
        ),

    mapping_reason TEXT,
    explanation TEXT,

    is_verified BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_mappings_paper_chunk
        FOREIGN KEY (paper_chunk_id)
        REFERENCES paper_chunks(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_mappings_code_block
        FOREIGN KEY (code_block_id)
        REFERENCES code_blocks(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_paper_code_mapping
        UNIQUE (paper_chunk_id, code_block_id),

    CONSTRAINT ck_mapping_similarity
        CHECK (
            similarity_score IS NULL
            OR similarity_score BETWEEN 0 AND 1
        )
);


/* =========================================================
   7. 일반 조회 인덱스
   ========================================================= */

CREATE INDEX idx_paper_chunks_paper
    ON paper_chunks(paper_id);

CREATE INDEX idx_paper_chunks_section
    ON paper_chunks(paper_id, section_title);

CREATE INDEX idx_code_blocks_repository
    ON code_blocks(repository_id);

CREATE INDEX idx_code_blocks_file
    ON code_blocks(repository_id, file_path);

CREATE INDEX idx_code_blocks_symbol
    ON code_blocks(symbol_name);

CREATE INDEX idx_mappings_paper_chunk
    ON paper_code_mappings(paper_chunk_id);

CREATE INDEX idx_mappings_code_block
    ON paper_code_mappings(code_block_id);

CREATE INDEX idx_paper_repositories_repository
    ON paper_repositories(repository_id);


SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;